Logic for wait in cloud-init runcmd

diff --git a/discovery/roles/configure_ochami/templates/cloud_init/ci-group-slurm_node_x86_64.yaml.j2 b/discovery/roles/configure_ochami/templates/cloud_init/ci-group-slurm_node_x86_64.yaml.j2
--- a/discovery/roles/configure_ochami/templates/cloud_init/ci-group-slurm_node_x86_64.yaml.j2
+++ b/discovery/roles/configure_ochami/templates/cloud_init/ci-group-slurm_node_x86_64.yaml.j2
@@ -69,20 +69,68 @@
             {{ ip_name_map[key] }} {{ key }}
 {% endfor %}
 
+        - path: /usr/local/bin/wait_for_ip.sh
+          permissions: '{{ file_mode_755 }}'
+          content: |
+            #!/bin/bash
+            LOGFILE="/var/log/wait_for_ip.log"
+            IP=$1
+            if [ -z "$IP" ]; then
+              echo "IP address is not provided, No wait required" | tee -a "$LOGFILE"
+              exit 0
+            fi
+            TIMEOUT=5
+            MAX_RETRIES=10
+            COUNT=0
+            echo "Waiting for $IP to become reachable..." | tee -a "$LOGFILE"
+            while true; do
+              if ping -c1 -W1 "$IP" &>/dev/null; then
+                  echo "$IP is up — proceeding." | tee -a "$LOGFILE"
+                  exit 0
+              fi
+              ((COUNT++))
+              if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
+                echo "IP $IP not reachable after $MAX_RETRIES attempts, giving up." | tee -a "$LOGFILE"
+                exit 1
+              fi
+              echo "IP $IP not reachable yet (attempt $COUNT). Retrying in $TIMEOUT seconds..." | tee -a "$LOGFILE"
+              sleep "$TIMEOUT"
+              done
       runcmd:
         - /usr/local/bin/set-hostname-by-mac.sh
+        - mkdir -p /var/log
+        - |
+          #!/bin/bash
+          LOGFILE="/var/log/wait_for_ip.log"
+          IP={{ ctld_list[0] }}
+          TIMEOUT=10
+          MAX_RETRIES=60
+          COUNT=0
+          echo "Waiting for $IP to become reachable..." | tee -a "$LOGFILE"
+          while true; do
+            if ping -c1 -W1 "$IP" &>/dev/null; then
+                echo "$IP is up — proceeding." | tee -a "$LOGFILE"
+                break
+            fi
+            ((COUNT++))
+            if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
+              echo "IP $IP not reachable after $MAX_RETRIES attempts, giving up." | tee -a "$LOGFILE"
+              exit 1
+            fi
+            echo "IP $IP not reachable yet (attempt $COUNT). Retrying in $TIMEOUT seconds..." | tee -a "$LOGFILE"
+            sleep "$TIMEOUT"
+            done
         - useradd -mG wheel -p '$6$VHdSKZNm$O3iFYmRiaFQCemQJjhfrpqqV7DdHBi5YpY6Aq06JSQpABPw.3d8PQ8bNY9NuZSmDv7IL/TsrhRJ6btkgKaonT.' testuser
         - groupadd -r {{ slurm_group_name }}
         - useradd -r -g {{ slurm_group_name }} -d {{ home_dir }} -s /sbin/nologin {{ user }}
 
-        - mkdir -p /var/log/slurm /var/run/slurm /var/spool /var/lib/slurm /etc/slurm/epilog.d /etc/munge
+        - mkdir -pv /var/log/slurm /var/run/slurm /var/spool /var/lib/slurm /etc/slurm/epilog.d /etc/munge
         - echo "{{ cloud_init_nfs_path }}/$(hostname -s)/var/log/slurm  /var/log/slurm   nfs defaults,_netdev 0 0" >> /etc/fstab
         - echo "{{ cloud_init_nfs_path }}/$(hostname -s)/var/spool      /var/spool       nfs defaults,_netdev 0 0" >> /etc/fstab
         - echo "{{ cloud_init_nfs_path }}/$(hostname -s)/etc/slurm/epilog.d     /etc/slurm/epilog.d      nfs defaults,_netdev 0 0" >> /etc/fstab
-        - echo "{{ cloud_init_nfs_path }}/$(hostname -s)/var/spool      /var/spool       nfs defaults,_netdev 0 0" >> /etc/fstab
         - echo "{{ cloud_init_nfs_path }}/$(hostname -s)/etc/munge      /etc/munge       nfs defaults,_netdev 0 0" >> /etc/fstab
         - chmod {{ file_mode }} /etc/fstab
-        - mount -a
+        - mount -av
 
         - yes | cp /etc/slurm/epilog.d/slurmd.service /usr/lib/systemd/system/
         - chown -R {{ user }}:{{ slurm_group_name }} /var/log/slurm
