40

diff --git a/.github/workflows/ansible-lint.yml b/.github/workflows/ansible-lint.yml
--- a/.github/workflows/ansible-lint.yml
+++ b/.github/workflows/ansible-lint.yml
@@ -41,7 +41,9 @@ jobs:
         echo $files_list
         for file in $files_list; do
           echo "Linting $GITHUB_WORKSPACE/$file"
-          ansible-lint "$GITHUB_WORKSPACE/$file"
+          if ! ansible-lint "$GITHUB_WORKSPACE/$file"; then
+            echo "Linting of $GITHUB_WORKSPACE/$file failed"
+          fi
         done
       shell: bash
 
